import { mkdtemp, readFile, rm, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import assert from "node:assert/strict";

import { updateProjectVersion } from "./update-version.mjs";

async function writeJson(path, value) {
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`);
}

async function createFixture() {
  const root = await mkdtemp(join(tmpdir(), "devdock-version-"));
  await mkdir(join(root, "src-tauri"), { recursive: true });

  await writeJson(join(root, "package.json"), {
    name: "devdock",
    private: true,
    version: "0.1.5",
    scripts: {},
  });
  await writeJson(join(root, "package-lock.json"), {
    name: "devdock",
    version: "0.1.5",
    lockfileVersion: 3,
    requires: true,
    packages: {
      "": {
        name: "devdock",
        version: "0.1.5",
      },
      "node_modules/example": {
        version: "0.1.5",
      },
    },
  });
  await writeFile(
    join(root, "src-tauri", "Cargo.toml"),
    `[package]
name = "devdock"
version = "0.1.5"
description = "A Tauri App"

[dependencies]
example = "0.1.5"
`,
  );
  await writeFile(
    join(root, "src-tauri", "Cargo.lock"),
    `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "android_system_properties"
version = "0.1.5"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "devdock"
version = "0.1.5"
dependencies = [
 "android_system_properties",
]
`,
  );
  await writeJson(join(root, "src-tauri", "tauri.conf.json"), {
    productName: "DevDock",
    version: "0.1.5",
    identifier: "com.wangqinghua.devdock",
  });

  return root;
}

test("updates every DevDock version location without touching dependency versions", async () => {
  const root = await createFixture();
  try {
    const changedFiles = await updateProjectVersion(root, "0.1.6");

    assert.deepEqual(changedFiles, [
      "package.json",
      "package-lock.json",
      "src-tauri/Cargo.toml",
      "src-tauri/Cargo.lock",
      "src-tauri/tauri.conf.json",
    ]);

    const packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
    const packageLock = JSON.parse(await readFile(join(root, "package-lock.json"), "utf8"));
    const cargoToml = await readFile(join(root, "src-tauri", "Cargo.toml"), "utf8");
    const cargoLock = await readFile(join(root, "src-tauri", "Cargo.lock"), "utf8");
    const tauriConfig = JSON.parse(
      await readFile(join(root, "src-tauri", "tauri.conf.json"), "utf8"),
    );

    assert.equal(packageJson.version, "0.1.6");
    assert.equal(packageLock.version, "0.1.6");
    assert.equal(packageLock.packages[""].version, "0.1.6");
    assert.equal(packageLock.packages["node_modules/example"].version, "0.1.5");
    assert.match(cargoToml, /version = "0\.1\.6"/);
    assert.match(cargoToml, /example = "0\.1\.5"/);
    assert.match(cargoLock, /name = "devdock"\nversion = "0\.1\.6"/);
    assert.match(cargoLock, /name = "android_system_properties"\nversion = "0\.1\.5"/);
    assert.equal(tauriConfig.version, "0.1.6");
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("rejects invalid semantic versions", async () => {
  await assert.rejects(
    () => updateProjectVersion("/tmp/not-used", "1.2"),
    /版本号必须是 SemVer/,
  );
});
